---
# tasks file for roles/apache
- name: install packages
  yum:
   name: "{{ item }}"
   state: latest
  loop: "{{ packages }}"
- name: start the services
  service:
   name: "{{ item }}"
   state: started
   enabled: yes
  loop: "{{ services }}"
- name: allow traffic in firewall
  firewalld:
   service: "{{ rule }}"
   state: enabled
   immediate: yes
   permanent: yes
- name: create a home
  template:
   src: index.html.j2
   dest: /var/www/html/index.html
  notify: restart httpd
