---
- name: hosts
  hosts: all
  remote_user: devops
  become: yes
  tasks:
     - name: copy 
       template:
        src: hosts.j2
        dest: /etc/myhost
       when: inventory_hostname in groups['dev']
